### ISSUE TITLE
Phana output not matching expected results for unit cell with 66 atoms

### ISSUE THREAD

**Issue by Emrahoo** [lingtikong/phana#12]
My unit cell contains 66 atoms, so I expect my pdisp.dat file to have 70 columns, but it only has 12 columns. What can I do to fix this?"

**Comment by lingtikong** [comment]
For a unit cell of 66 atoms, one would expect 4+66*3 = 202 columns in pdisp.dat. How does the figure look like if you use gnuplot to visualize the dispersion? Does it contain the correct number of lines?

**Comment by Emrahoo** [comment]
Dear Professor Lingti Kong,

Thank you for your response and for taking the time to respond.
I wanted to apologize for my mistake regarding the number of curves. You were correct in stating that we should have 66 X 3 curves, and I now understand that the pdisp.dat file has 66 X 3 + 4 columns, which are written in a couple of lines. I apologize for any confusion or inconvenience this may have caused, and I appreciate your patience in helping me understand this better.
Thank you again for your time and assistance.

Best regards, Mohammadreza Emrahpour

**Comment by lingtikong** [comment]
Great, thanks for the feedback.
