### ISSUE TITLE
Phonon dispersion using fix-phonon

### ISSUE THREAD

**Issue by gbsouza1997** [lingtikong/phana#13]
Dear Dr.  Kong

I’m trying to use the “fix-phonon” to calculate the phonon dispersion for MoS2 Monolayer using a potential i’ve been developing using machine learning and DFT data. I was able to reproduce the phonon dispersion using lammps as a tool in a package called Alamode ( T. Tadano, Y. Gohda, and S. Tsuneyuki, J. Phys.: Condens. Matter 26 , 225402 (2014)) without problems at gamma

I’m having problems next gamma. the phonon dispersion explodes to negative values and positive values of order of >10^3 thz. If i include the option “-r” at “./phana” even if knowing I should not use it because I’m not including charges on my systems the problem of exploding values at gamma dissapear but I end up with highly unnacurate values for frequencies at Gamma.

I’m making simulations using 50x50x1 cell (7500 atoms total) and for timestep = 1 fs for 5000000 steps.

Here’s the input im using:

> atom_style atomic
boundary p p p
read_data MoS2.data.huge_phon.pos
velocity all create 300 35131 dist gaussian
group S type 1
group Mo type 2
pair_style aenet
pair_coeff * * v-1 S Mo good_phonon0.ann S Mo
timestep 0.001 #ps
thermo 500 # intervalo para mostrar output instantaneos.
neighbor 2.0 bin
neigh_modify every 3 delay 0 check yes
dump myDump all xyz 1000 dump.MoS2_300K.lang.xyz
dump_modify myDump element S Mo
fix 1 all langevin 300 300 0.1 73504 zero yes
fix 2 all nve
fix 3 all phonon 10 50000 1000000 mos2_huge_map.in mos2Phonon_lang nasr 50
run 5000000

thanks in advance for the help

**Comment by lingtikong** [comment]
I am not sure if it helps, but please try to add fix-recenter:
fix 4 all recenter NULL NULL INIT

phana -r should work for all system with more than 1 atom in a unit cell.
