### ISSUE TITLE
compatibily issue with c++/7/bits/stl_algobase.h

### ISSUE THREAD

**Issue by 1314DA** [lingtikong/phana#3]
During compilation if the phana code the following errors are thrown by the library 'stl_algobase.h'

* stl_algobase.h:243:56: error: macro "min" passed 3 arguments, but takes just 2
* /usr/include/c++/7/bits/stl_algobase.h:219:5: error: expected ‘)’ before ‘const’

The latter error appears in several variants, which indicates to me that maybe some syntax is not ok?!
A quick google search just provided me with the hint that the error originates from incompatibilities between the included c++ libraries.

My process was as follows:
* download 'clapack', 'tricubic', 'spglib' and 'fftw3' from the provided sources in the README
* compile them; all the checks finished successfully
* specify the locations of the libraries in the makefile
* go to the phana main directrory and type 'make'

**Comment by lingtikong** [comment]
This should be caused by the conflict between the definions of macro MIN and/or MAX. I cannot reproduce this error on my computer, and cannot provide a solution at this moment. Perhaps this might work:
sed -i 's/MIN/MMIINN/g'  *.cpp  *.h
sed -i 's/MAX/MMAAXX/g' *.cpp *.h

**Comment by denzelayala1** [comment]
@lingtikong @1314DA 

I have reproduced this error on Ubuntu 20.04LTS on Windows Subsystem for Linux (WSL) and again on a separate machine on Debian 10. 

The conflict is between CLAPACK and the standard library so your fix wont work.
 ```
g++ -Wno-unused-result -O3   -DFFTW3 -I/opt/clapack/3.2.1/include -I/opt/tricubic/1.0/include  -I/opt/fftw/3.3.8/include -c main.cpp
In file included from /usr/include/c++/9/bits/char_traits.h:39,
                 from /usr/include/c++/9/ios:40,
                 from /usr/include/c++/9/istream:38,
                 from /usr/include/c++/9/sstream:38,
                 from /usr/include/c++/9/complex:45,
                 from phonon.h:6,
                 from main.cpp:4:
/usr/include/c++/9/bits/stl_algobase.h:246:56: error: macro "min" passed 3 arguments, but takes just 2
  246 |     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
      |                                                        ^
In file included from interpolate.h:11,
                 from dynmat.h:8,
                 from main.cpp:3:
/opt/clapack/3.2.1/include/f2c.h:159: note: macro "min" defined here
  159 | #define min(a,b) ((a) <= (b) ? (a) : (b))
      |
```

**Comment by denzelayala1** [comment]
An Update,

While I wasn't able to compile the software I found that the precompiled binary works well enough.  The link is below.

https://code.google.com/archive/p/fix-phonon/downloads

**Comment by lingtikong** [comment]
Pls try the precompiled version here:
https://github.com/lingtikong/phana/tree/master/precompiled

I will try to find the solution when I have time.

**Comment by lingtikong** [comment]
I think the problem is solved: by including "complex.h" before "clapack.h" in interpolate.h seems to work. pls confirm, thanks.

**Comment by 1314DA** [comment]
I just compiled phana successfully by simply making the insertion you suggested.
Thank you very much for your help!

Sorry, I had some problems getting clapack to work, which is why my reply is a little late.
