### ISSUE TITLE
Their is no libclapack.a and clapack_LINUX.a in /opt/clapack/3.2.1/lib to create symbolic link, kindly help

### ISSUE THREAD

**Issue by owaisahmad18** [lingtikong/phana#6]

**Comment by lingtikong** [comment]
Please check if it works by following the instructions of clapack:

http://www.netlib.org/clapack/readme.install

在 2021-10-27 18:50, Owais Ahmad 写道:

**Comment by owaisahmad18** [comment]
Actually i have already tried this , same issue with this one as well.

**Comment by lingtikong** [comment]
After the compilation, please check the SRC and the root directory of 
clapack; the generated *.a files should be there.

在 2021-10-29 12:48, Owais Ahmad 写道:

**Comment by owaisahmad18** [comment]
I have already checked, same issue. If u have the missing files in the compiled version with you, kindly share.

**Comment by lingtikong** [comment]
Please try the following steps:

1) Download clapack from the office website, e.g.:

wget http://www.netlib.org/clapack/clapack.tgz

2) Uncompress the source file:

tar xzvf clapack.tgz

3) Get into the directory:

cd CLAPACK-3.2.1/

4) Compile:

cp make.inc.example make.inc

cd BLAS/SRC;  make

cd ../..//F2CLIBS/libf2c; make

cd ../../INSTALL; make

cd ../SRC; make

cd ..; ls *.a

ln -s blas_LINUX.a libblas.a

ln -s lapack_LINUX.a libclapack.a

ln -s lapack_LINUX.a liblapack.a


It works on my computer.

在 2021-11-01 13:16, Owais Ahmad 写道:

**Comment by owaisahmad18** [comment]
Thanks a lot it worked!!, Just as a note for others, in original instructions the command is ...
ln -s clapack_LINUX.a libclapack.a but their is no clapack_LINUX.a so you should link lapack_LINUX.a to libclapack.a and to liblapack.a both.
